parameters:
    graviton.generator.dynamicbundle.dir: "src/"
    graviton.version.desired_versions: []
    graviton.version.self_package_name: graviton/graviton
    graviton.sentry.dontReport: []
    graviton.version.ext_list: []
    graviton.generator.ensure_indexes: ~

# Synfony Framework Configuation
# see http://symfony.com/doc/current/reference/configuration/framework.html
framework:
    trusted_proxies: '192.0.0.0/8,172.0.0.0/8,10.0.0.0/8'
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix' ]
    http_method_override: false
    handle_all_throwables: false
    secret: "%secret%"
    php_errors:
        log: true
    router:
        resource: "%kernel.project_dir%/config/routes.yaml"
        type: yaml
        utf8: true
        strict_requirements: ~
    form:
        enabled: false
    csrf_protection: false
    annotations:
        enabled: false
    validation:
        enabled: false
        enable_attributes: false
        email_validation_mode: html5
    default_locale: "%locale%"
    trusted_hosts: ~
    fragments: ~

######### ORIGINAL UNTEN

# disable rql parser listener
graviton_rql_parser:
    activate_listener: false

graviton_common:
    mongo_document_manager_service_id: doctrine_mongodb.odm.default_document_manager
    cache:
        instance_id: "%graviton.cache.instance_id%"
        redis_host: "%graviton.cache.redis.host%"
        redis_port: "%graviton.cache.redis.port%"
        redis_db: 10
        adapter_override: null
    audit:
        enabled: "%security.audit.enabled%"
        active_user_tracking_enabled: false # no use tracking
        fallback_mongodb: false # no mongodb fallback!
        app_name: 'graviton'
        response_header_name: 'X-Graviton-Audit-ID'
        skip_on_header_presence: 'X-Gateway-Audit-ID' # do nothing if downstream already recorded the event!
        record_payload: "%security.audit.record_payload%"
        record_payload_exceptions: "%security.audit.record_payload_exception_list%"
        ignore_methods: "%security.audit.ignore_methods%"
        logger_url: "%security.audit.logger_url%"
    http_client:
        options:
            stream: false
            http_errors: false
            cookies: true
        verify_peer: "%graviton.core.httpclient.verifyPeer%"
        debug_requests: "%graviton.core.httpclient.debugRequests%"
        debug_max_length: "%graviton.core.httpclient.debugMaxLength%"
    deployment:
        check_package_name: "%graviton.version.self_package_name%"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller: null

# DoctrineMongoDB Configuration
# see: http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/config.html
doctrine_mongodb:
    default_database: "%graviton.mongodb.default.server.db%"
    proxy_dir: "%kernel.project_dir%/src/Doctrine/Proxies"
    hydrator_dir: "%kernel.project_dir%/src/Doctrine/Hydrators"
    connections:
        default:
            server: "%graviton.mongodb.default.server.uri%"
            options: {}
    document_managers:
        default:
            auto_mapping: true
            metadata_cache_driver:
                type: "service"
                id: "graviton.common.cache.adapter.app"


# JmsSerializerBundle Configuration
# see: http://jmsyst.com/bundles/JMSSerializerBundle/master/configuration
jms_serializer:
    handlers:
        datetime:
            default_format: Y-m-d\TH:i:sO
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
        separator: ''
    default_context:
        serialization:
            serialize_null: false
    metadata:
        cache: file
        debug: "%kernel.debug%"
        auto_detection: true
        file_cache:
          dir: "%kernel.cache_dir%/serializer"

flysystem:
    storages:
        storage.local:
            adapter: 'local'
            options:
                directory: "%graviton.file.local.storage_directory%"
        storage.s3:
            adapter: 'asyncaws'
            options:
                client: graviton.file.asyncs3.client
                bucket: "%graviton.file.s3.bucket%"
                prefix: ''
        storage.webdav:
            adapter: 'graviton.file.webdav.adapter'
        storage.backend:
            adapter: 'lazy'
            options:
                source: 'storage.%graviton.file.backend%'

graviton_core:
    service_name:
        - graviton.core.static.version.get
        - graviton.security.static.whoami.get
    uri_whitelist:
        - /core/version
        - /person/whoami

sentry:
    dsn: "%graviton.sentry.dsn%"
    register_error_listener: false
    tracing:
        enabled: false
    options:
        # see https://github.com/getsentry/sentry-symfony/issues/421
        ## as we cannot filter here, we disable all and enable those that we want
        default_integrations: false
        ignore_exceptions: "%graviton.sentry.dontReport%"
        integrations:
            - 'Sentry\Integration\RequestIntegration'
            - 'Sentry\Integration\TransactionIntegration'
            - 'Sentry\Integration\FrameContextifierIntegration'
            - 'Sentry\Integration\EnvironmentIntegration'
            - 'Sentry\Integration\ModulesIntegration'
        environment: "%kernel.environment%"
