security:
    providers:
        default:
            id: Graviton\SecurityBundle\Authentication\UserProvider

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        main:
            pattern: .*
            provider: default
            entry_point: Graviton\SecurityBundle\Authenticator\SameSubnetAuthenticator
            custom_authenticators:
                - Graviton\SecurityBundle\Authenticator\SameSubnetAuthenticator
                - Graviton\SecurityBundle\Authenticator\UserHeaderAuthenticator
            stateless: true
