services:
    graviton.analytics.defaut_controller:
        class: Graviton\AnalyticsBundle\Controller\DefaultController
        public: true
        tags: ['controller.service_arguments']
        arguments:
            - "@graviton.analytics.service_manager"

    graviton.analytics.command.analyticscreateview:
        class: Graviton\AnalyticsBundle\Command\AnalyticsCreateViewCommand
        arguments:
            - "@doctrine_mongodb.odm.default_document_manager"
            - "%graviton.mongodb.default.server.db%"
            - "%analytics.services%"
        tags:
            -
                name: console.command

    graviton.analytics.analytics_manager:
        class: Graviton\AnalyticsBundle\Manager\AnalyticsManager
        arguments:
            - "@doctrine_mongodb.odm.default_document_manager"
            - "%graviton.mongodb.default.server.db%"
            - "@graviton.document.service.dateconverter"
            - "@event_dispatcher"

    graviton.analytics.service_manager:
        class: Graviton\AnalyticsBundle\Manager\ServiceManager
        arguments:
            - "@request_stack"
            - "@graviton.analytics.analytics_manager"
            - "@graviton.document.service.dateconverter"
            - "@router"
            - "%analytics.services%"
        tags:
            - name: kernel.event_listener
              event: generate.global.schema
              method: onSchemaGeneration

    graviton.analytics.homepage_listener:
        class: Graviton\AnalyticsBundle\Listener\HomepageRenderListener
        arguments:
            - "@graviton.analytics.service_manager"
        tags:
            - { name: kernel.event_listener, event: homepage.render, method: onRender }
