parameters:
  graviton.swagger.generation_dir: "%kernel.project_dir%/app/"

services:

    graviton.swagger.schema.model:
      class: Graviton\SchemaBundle\Model\SchemaModel
      arguments:
        - '@=service("kernel").locateResource("@GravitonSchemaBundle/Resources/config/schema/SchemaModel.json")'

    # swagger service - a service that generates swagger spec -->
    graviton.rest.apidoc:
        class: Graviton\SwaggerBundle\Service\Swagger
        arguments:
          - "@router"
          - "@graviton.rest.restutils"
          - "@graviton.swagger.schema.model"
          - "@graviton.schema.utils"
          - "%graviton.core.version.data%"

    graviton.swagger.filesystem.command:
        class: Symfony\Component\Filesystem\Filesystem

    graviton.swagger.command.swaggergenerate:
        class: Graviton\SwaggerBundle\Command\SwaggerGenerateCommand
        arguments:
          - "%graviton.generator.hash.all%"
        tags:
          -
            name: console.command
        calls:
          -
            method: setRootDir
            arguments:
              - "%graviton.swagger.generation_dir%"
          -
            method: setFilesystem
            arguments:
              - "@graviton.swagger.filesystem.command"
          -
            method: setApidoc
            arguments:
              - "@graviton.rest.apidoc"

    graviton.swagger.filesystem.finder:
        class: Symfony\Component\Finder\Finder

    graviton.swagger.controller.swagger:
        class: Graviton\SwaggerBundle\Controller\SwaggerController
        public: true
        arguments:
          - "@graviton.swagger.filesystem.finder"
          - "%graviton.swagger.generation_dir%"
