parameters:
  # generator
  graviton.generator.dynamicbundle.dir: null
  generator.bundlebundle.additions: []
  #graviton.generator.synthetic_fields: 'int:tenant'
  graviton.generator.synthetic_fields: null
  graviton.generator.synthetic_fields_expose_on: null
  #graviton.generator.ensure_indexes: hans,test2
  graviton.generator.ensure_indexes: null

  # /core/version params
  graviton.version.self_package_name: graviton/graviton
  graviton.version.desired_versions:
    - symfony/framework-bundle
  graviton.version.ext_list:
    - mongodb

  # sentry
  graviton.sentry.dontReport:
    - Symfony\Component\HttpKernel\Exception\HttpExceptionInterface
    - Graviton\JsonSchemaBundle\Exception\ValidationException
    - Graviton\RqlParser\Exception\SyntaxErrorException
    - Graviton\AnalyticsBundle\Exception\AnalyticUsageException
    - Graviton\ExceptionBundle\Exception\NotFoundException
