# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        graviton_airlock_authentication_key_user_provider:
            id: graviton_airlock_authentication_key_user_provider

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # graviton access restriction
        secured_area:
            #  no pattern means matches all routes
            stateless: true
            simple_preauth:
                authenticator: graviton_airlock_authentication_key_authenticator

    access_decision_manager:
        # strategy can be: affirmative, unanimous or consensus
        strategy: unanimous #every voter has to grant access
