
framework:
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: "stream"
            path: "%graviton.log.path%"
            level: "debug"
            channels: ["!event"]
            formatter: Graviton\CommonBundle\Component\Logging\SecurityFormatter
