services:
    graviton.file.request_manager:
        class: "%graviton.file.request_manager.class%"
        arguments:
            - "@?request_stack"

    graviton.file.file_manager:
        class: "%graviton.file.file_manager.class%"
        public: true
        arguments:
            - "@storage.backend"
        calls:
          -
            method: setAllowedMimeTypes
            arguments:
              - "%graviton.file.allowed.mime_types%"
          -
            method: setReadFileSystemMimeType
            arguments:
              - "%graviton.file.read_filesystem_mimetype%"

    graviton.file.asyncs3.client:
      class: AsyncAws\S3\S3Client
      arguments:
        - region: "%graviton.file.s3.region%"
          accessKeyId: "%graviton.file.s3.credentials.key%"
          accessKeySecret: "%graviton.file.s3.credentials.secret%"
          endpoint: "%graviton.file.s3.endpoint%"
          pathStyleEndpoint: true

    graviton.file.webdav.client:
      class: Sabre\DAV\Client
      arguments:
        - baseUri: '%graviton.file.webdav.baseuri%'
          userName: '%graviton.file.webdav.username%'
          password: '%graviton.file.webdav.password%'

    graviton.file.webdav.adapter:
      class: League\Flysystem\WebDAV\WebDAVAdapter
      arguments:
        - '@graviton.file.webdav.client'

    graviton.file.controller.file:
        class: "%graviton.file.controller.file.class%"
        public: true
        parent: "graviton.rest.controller"
        calls:
          -
            method: setModel
            arguments:
                -  "@?gravitondyn.file.model.file"
          -
            method: setFileManager
            arguments:
                - "@graviton.file.file_manager"
          -
            method: setRequestManager
            arguments:
                - "@graviton.file.request_manager"

