services:

    Graviton\FileBundle\Manager\FileManager:
        arguments:
            - '@storage.backend'
            - '@Graviton\RestBundle\Service\RestUtils'
            - '@psr17_factory'
            - "%graviton.file.allowed.mime_types%"

    graviton.file.asyncs3.client:
      class: AsyncAws\S3\S3Client
      arguments:
        - region: "%graviton.file.s3.region%"
          accessKeyId: "%graviton.file.s3.credentials.key%"
          accessKeySecret: "%graviton.file.s3.credentials.secret%"
          endpoint: "%graviton.file.s3.endpoint%"
          pathStyleEndpoint: true

    graviton.file.webdav.client:
      class: Sabre\DAV\Client
      arguments:
        - baseUri: '%graviton.file.webdav.baseuri%'
          userName: '%graviton.file.webdav.username%'
          password: '%graviton.file.webdav.password%'

    graviton.file.webdav.adapter:
      class: League\Flysystem\WebDAV\WebDAVAdapter
      arguments:
        - '@graviton.file.webdav.client'

    Graviton\FileBundle\Controller\FileController:
      parent: "graviton.rest.controller"
      calls:
        -
          method: setModel
          arguments:
              - "@?gravitondyn.file.model.file"
        -
          method: setFileManager
          arguments:
              - '@Graviton\FileBundle\Manager\FileManager'

