Graviton\AuditTrackingBundle\Document\AuditTracking:
    exclusion_policy: NONE
    read_only: true
    properties:
        data:
            expose: true
            accessor:
                getter: getData
        ref:
            type: Graviton\DocumentBundle\Entity\ExtReference
            accessor:
                getter: getRef