imports:
    - { resource: config_test.yml }

# in this environment, data restrictions are enabled
parameters:

    graviton.translator.default.language: en

    graviton.rest.data_restriction.map:
        x-graviton-client: "int:clientId"
