<?php
/**
 * Repository for accessing Languages
 */

namespace Graviton\I18nBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @category I18nBundle
 * @package  Graviton
 * @link     http://swisscom.com
 */
class LanguageRepository extends DocumentRepository
{
}
