<?php
/**
 * Repository for accessing Languages
 */

namespace Graviton\I18nBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @category I18nBundle
 * @package  Graviton
 * @author   List of contributors <https://github.com/libgraviton/graviton/graphs/contributors>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://swisscom.ch
 */
class LanguageRepository extends DocumentRepository
{
}
