<?php
/**
 * Repository for accessing TranslatableLanguages
 *
 * This is only needed due to them schema generator needed it.
 */

namespace Graviton\I18nBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TranslatableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author   List of contributors <https://github.com/libgraviton/graviton/graphs/contributors>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://swisscom.ch
 */
class TranslatableLanguageRepository extends DocumentRepository
{
}
