<?php
/**
 * Repository for accessing Translatables
 */

namespace Graviton\I18nBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TranslatableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @category I18nBundle
 * @package  Graviton
 * @author   Lucas Bickel <lucas.bickel@swisscom.com>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://swisscom.com
 */
class TranslatableRepository extends DocumentRepository
{
}
