jms_serializer:
    metadata:
        debug: "%kernel.debug%"
        auto_detection: true
        directory:
            name: GeneratorBundle
            namespace_prefix: Graviton\GeneratorBundle
            path: "@GravitonGeneratorBundle/Resources/config/serializer"
