
monolog:
    handlers:
        main:
            type: "stream"
            path: "%graviton.log.path%"
            level: "%graviton.log.level%"
            channels: ["!event", "!doctrine", "!php"]
            formatter: Graviton\CommonBundle\Component\Logging\SecurityFormatter
        sentry:
            type: sentry
            level: !php/const Monolog\Logger::ERROR
            hub_id: Sentry\State\HubInterface
