<?php
/**
 * Repository for accessing Apps
 */

namespace Graviton\CoreBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * AppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author   List of contributors <https://github.com/libgraviton/graviton/graphs/contributors>
 * @license  https://opensource.org/licenses/MIT MIT License
 * @link     http://swisscom.ch
 */
class AppRepository extends DocumentRepository
{
}
