<?php
/**
 * Repository for accessing Products
 */

namespace Graviton\CoreBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @category GravitonDocumentBundle
 * @package  Graviton
 * @link     http://swisscom.com
 */
class ProductRepository extends DocumentRepository
{
}
