
services:

  # needs to activate in test env in order to test streamed responses
  Graviton\Tests\StreamedReponseTestListener:
    tags:
      - name: kernel.event_listener
        event: kernel.response
        method: onKernelResponse

