openapi: 3.1.0
paths:
  /core/version:
    get:
      summary: "Shows version information of this instance"
      operationId: "coreVersionGet"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GravitonVersionInformation"
components:
  schemas:
    GravitonVersionInformation:
      type: object
      properties:
        versions:
          type: object
          description: An object with version information
          additionalProperties:
            type: string
