
services:
    Graviton\LogBundle\Listener\RequestIdListener:
        tags:
            - name: "kernel.event_listener"
              event: "kernel.request"
              method: "onKernelRequest"
              priority: 900

    Graviton\LogBundle\Monolog\Processor\RequestIdProcessor:
        arguments:
            - "@request_stack"
        tags:
          - { name: monolog.processor }
