<?php
/**
 * generate url from raw db data
 *
 * Here we get the raw structure that has been hydrated for $ref link cases
 * by doctrine and replace it with a route generated by the symfony router.
 * We do this in it's own listener due to the fact that there is no way that
 * we can inject anything useable into the default odm hydrator and it looks
 * rather futile to hack it so we can use our own custom hydration code.
 */

namespace Graviton\DocumentBundle\Listener;

use Graviton\DocumentBundle\Service\ExtReferenceConverterInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpKernel\Event\FilterResponseEvent;
use Graviton\Rql\Event\VisitNodeEvent;

/**
 * @author   List of contributors <https://github.com/libgraviton/graviton/graphs/contributors>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://swisscom.ch
 */
class ExtReferenceSearchListener
{
    /**
     * @var ExtReferenceConverterInterface
     */
    private $converter;

    /**
     * @var array
     */
    private $fields;

    /**
     * @var Request
     */
    private $request;

    /**
     * construct
     *
     * @param ExtReferenceConverterInterface $converter Extref converter
     * @param array                          $fields    map of fields to process
     * @param RequestStack                   $requests  request
     */
    public function __construct(ExtReferenceConverterInterface $converter, array $fields, RequestStack $requests)
    {
        $this->converter = $converter;
        $this->fields = $fields;
        $this->request = $requests->getCurrentRequest();
    }

    /**
     * @param VisitNodeEvent $event node event to visit
     *
     * @return VisitNodeEvent
     */
    public function onVisitNode(VisitNodeEvent $event)
    {
        $node = $event->getNode();
        $builder = $event->getBuilder();

        $route = $this->request->attributes->get('_route');

        if (!array_key_exists($route, $this->fields)) {
            throw new \LogicException('Missing ' . $route . ' from extref fields map.');
        }

        $fields = $this->fields[$route];

        if (!in_array(strtr($node->getField(), ['..' => '.0.']), $fields)) {
            return $event;
        }

        try {
            $dbRef = $this->converter->getDbRef($node->getValue());
        } catch (\InvalidArgumentException $e) {
            //make up some invalid refs to ensure we find nothing if an invalid url was given
            $dbRef['$ref'] = false;
            $dbRef['$id'] = false;
        }

        $builder->field(strtr($node->getField(), ['$' => '', '..' => '.0.']) . '.$ref')->equals($dbRef['$ref']);
        $builder->field(strtr($node->getField(), ['$' => '', '..' => '.0.']) . '.$id')->equals($dbRef['$id']);

        $event->setNode(null);
        $event->setBuilder($builder);
        return $event;
    }
}
