<?php

namespace Graviton\PersonBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ConsultantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @category PersonBundle
 * @package  Graviton
 * @author   Lucas Bickel <lucas.bickel@swisscom.com>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://swisscom.com
 */
class ConsultantRepository extends DocumentRepository
{
}
