<?php
/**
 * CustomerDiffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

namespace Graviton\PersonBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * @author   List of contributors <https://github.com/libgraviton/graviton/graphs/contributors>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://swisscom.ch
 */
class CustomerDiffRepository extends DocumentRepository
{
}
