<?php

namespace Graviton\PersonBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * PersonContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonContactRepository extends DocumentRepository
{
}