<?php

namespace Graviton\ConsultationBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ConsultationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @category ConsultationBundle
 * @package  Graviton
 * @author   Manuel Kipfer <manuel.kipfer@swisscom.com>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://swisscom.com
 */
class ConsultationRepository extends DocumentRepository
{
}
