name: Graviton CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  symfony:
    name: Graviton CI (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest

    # Docs: https://docs.github.com/en/actions/using-containerized-services
    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017/tcp

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.3']
        experimental: [false]
        # these are allowed to fail!
        #include:
        #  - php-versions: '8.3'
        #    experimental: true

    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: php-coveralls/php-coveralls
          extensions: mbstring, xml, ctype, iconv, intl, amqp, mongodb, zip
          coverage: pcov

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Prepare tests
        run: |
          echo "APP_ENV=test" > .env.local
          echo "APP_DEBUG=0" >> .env.local
          echo "MONGODB_URI=${MONGODB_URI}" >> .env.local
          
          composer configure
          bash prepare-for-tests.sh
          cat app/config/parameters.yml
          
          composer check
        env:
          MONGODB_URI: mongodb://127.0.0.1:${{ job.services.mongodb.ports['27017'] }}/db

      - name: Run tests
        run: |
          php -dpcov.directory=${PWD}/src/Graviton -dpcov.exclude="~vendor~" vendor/bin/phpunit --coverage-clover ${PWD}/coverage.clover --log-junit ${PWD}/phpunit_junit.xml

      - name: Upload Coveralls coverage
        run: |
          php-coveralls --coverage_clover=${PWD}/coverage.clover --root_dir=${PWD}/src/Graviton/ -o /tmp/coveralls.json -v
        env:
          COVERALLS_REPO_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          COVERALLS_FLAG_NAME: '${{ matrix.php-versions }}'

      - uses: ashley-taylor/junit-report-annotations-action@1.4
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: phpunit_junit.xml
          name: "PHPUnit Report ${{ matrix.php-versions }}"
